version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: io.grpc:grpc-testing
    versions:
    - 1.35.0
    - 1.36.0
    - 1.36.1
  - dependency-name: org.springframework.boot:spring-boot-starter-parent
    versions:
    - 2.4.3
  - dependency-name: io.github.lognet:grpc-spring-boot-starter
    versions:
    - 4.4.3
    - 4.4.4
